# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9bd60b90f0923a4d92b99b18f126c23ebb7b28598c2e5cd5ac801ad053f99037d08b77a26be5892a5ed225b82276e2e92407f9e899b221f331ffc55d25ff394f

test:
  secret_key_base: dc39856fded6f2f9c4ee7d8ea67b752e45b978480776880929001efceef588618c463bd717649662201ac19da85e7774530d2f4de3b4d41951a0edce6e3eedd7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
